server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-center
  profiles:
    active: dev

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # 命令空间
        # namespace: 23be7023-3d9e-4a15-bc92-db83448d831d
        # 集群
        cluster-name: BJ
        metadata:
          instance: a
          version: v1
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          # 用来指定topic
          destination:  stream-test-topic
          group: binder-group
        my-input:
          # 用来指定topic
          destination:  stream-my-topic
          group: my-group
        add-bonus-input:
          destination:  add-bonus-stream
          group: add-bonus-stream-group

  zipkin:
    base-url: http://localhost:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
      # 抽样率默认10%
      probability: 1.0


rocketmq:
  name-server: localhost:9876
  producer:
    group: test-group

jwt:
  secret: TYk2sTasdkng669_akgFG@
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600
