server:
  port: 8040

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enabled: true
      routes:
        - id: after_route
          uri: lb://user-center
          predicates:
            - TimeBetween=上午9:00,下午10:00
          filters :
            - PreLog=a,b
            - AddRequestHeader=X-Request-Foo,Bar
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always